#
# Packages the sample Linux app for Ubuntu.
# See: https://github.com/mapbox/mapbox-gl-native/tree/master/platform/linux
#

name: mapbox-demo
base: core18
version: '20190421-master'
summary: A simple map application for Linux.
description: |
  A simple map application and test suite for Linux, based on Mapbox GL Native
  and GLFW. Keyboard shortcuts for testing functionality are logged to the
  console when the test app is started. Please note that to run the app you
  need to set up a MAPBOX_ACCESS_TOKEN environment variable with a valid
  Mapbox access token (you can get a free one at https://www.mapbox.com).

grade: stable
confinement: strict

apps:
  mbgl-glfw:
    command: bin/mbgl-glfw

parts:
  mbgl-glfw:
    plugin: dump
    source-type: git
    source-branch: master
    source: https://github.com/mapbox/mapbox-gl-native
    override-build: |
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      nvm install 8.15.1
      sed -i '/ca-bundle.crt/d' platform/default/src/mbgl/storage/http_file_source.cpp
      make clean glfw-app
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp build/linux-x86_64/Debug/mbgl-glfw $SNAPCRAFT_PART_INSTALL/bin/mbgl-glfw
    stage:
      - bin/
      - usr/lib
    prime:
      - bin/
      - usr/lib
    build-packages:
      - automake
      - build-essential
      - ccache
      - cmake
      - cmake-data
      - curl
      - git
      - libcurl4-openssl-dev
      - libglu1-mesa-dev
      - libllvm3.9
      - libpng-dev
      - libsqlite3-dev
      - libtool
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - make
      - pkg-config
      - python-pip
      - x11proto-randr-dev
      - x11proto-xext-dev
      - x11proto-xf86vidmode-dev
      - xutils-dev
      - zlib1g-dev
    stage-packages:
      - libx11-6
      - libasn1-8-heimdal
      - libcurl4-openssl-dev
      - libgl1
      - libglvnd0
      - libglx0
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
